-- AlterTable: Add Energy Equation fields to SleepLog
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "caffeinePastNoon" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "caffeineHoursBefore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "screenMinBefore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "gotMorningLight" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "exercisedToday" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "exerciseHoursBefore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SleepLog" ADD COLUMN IF NOT EXISTS "lastMealHoursBefore" INTEGER NOT NULL DEFAULT 0;
